{{- if .Values.chaosTesting.enabled }}
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: {{ include "springboot-feature-flag.fullname" . }}-chaos
  labels:
    {{- include "springboot-feature-flag.labels" . | nindent 4 }}
    chaos-engine: "enabled"
spec:
  appinfo:
    appns: {{ .Values.service.namespace | default "production" }}
    applabel: app={{ include "springboot-feature-flag.fullname" . }}
    appkind: deployment
  # Chaos experiments to be executed
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: POD_LABEL
              value: app={{ include "springboot-feature-flag.fullname" . }}
            - name: TOTAL_CHAOS_DURATION
              value: "30"
    - name: network-loss
      spec:
        components:
          env:
            - name: NETWORK_PACKET_LOSS_PERCENT
              value: "100"
            - name: TOTAL_CHAOS_DURATION
              value: "60"
    - name: cpu-hog
      spec:
        components:
          env:
            - name: CPU_CORE
              value: "1"
            - name: TOTAL_CHAOS_DURATION
              value: "60"
{{- end }}
