apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feature-flag-service.fullname" . }}
  labels:
    {{- include "feature-flag-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "feature-flag-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "feature-flag-service.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "feature-flag-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityPolicy | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: "{{ .value }}"
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 14 }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}